### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by prakashmalviya** [zanysoft/laravel-pdf#1]
Hi
When I use position absolute in my html I have below error:

ErrorException in mpdf.php line 17074: 
A non-numeric value encountered

.myfixed2 { position: fixed;
    	overflow: auto;
    	right: 0;
    	bottom: 0mm;
    	width: 65mm;
    	border: 1px solid #880000;
    	background-color: #FFEEDD;
    	background-gradient: linear #dec7cd #fff0f2 0 1 0 0.5;
    	padding: 0.5em;
    	font-family:sans;
    	margin: 0;
    	rotate: 90;
    }

> <div class="myfixed2">test text.</div>'

`$pdf = PDF::Make();
$pdf->loadView('print', compact('bill', 'duplicate_invoice', 'diagnosis', 'layout'));
$view = view('bill.partials.forms.print_revision', compact('bill', 'diagnosis'));
return $pdf->download("bill.pdf");`

**Comment by zanysoft** [comment]
Please use valid and supported CSS.  (use unit with margin and right values like 0px or 0mm etc. )
You may see supported list of CSS rules here: [supported css rules](https://mpdf.github.io/css-stylesheets/supported-css.html)
