### ISSUE TITLE
each() function is deprecated and mpdf/mpdf v6

### ISSUE THREAD

**Issue by Benyamin001** [zanysoft/laravel-pdf#3]
we have  this error for PHP 7.2 

(1/1) ErrorExceptionThe each() function is deprecated. This message will be suppressed on further calls
--
in mpdf.php (line 10894)

each() function is deprecated and mpdf/mpdf update his package to support PHP 7.2 

Please update Thanks

**Comment by idmeneo** [comment]
Same here, can you do something ?
Thx
